## Video
## Hardware decoding
vo=gpu-next
gpu-api=auto
hwdec=auto
hwdec-codecs=all

## Behavior (personal preference)
keep-open=yes
save-position-on-quit=yes

## Languages
slang=eng,en,enUS,en-US          # automatically select these subtitles (decreasing priority)
alang=jpn,ja,eng,en,enUS,en-US,hin,hi     		# automatically select these audio tracks (decreasing priority)

## Screenshots
screenshot-format=png
screenshot-dir=~/Pictures/mpv
screenshot-template="%F-%p-%n"

## UOSC
# uosc provides seeking & volume indicators (via flash-timeline and flash-volume commands)
# if you decide to use them, you don't need osd-bar
osd-bar=no

# uosc will draw its own window controls and border if you disable window border
border=no

