[tools]
agy = "latest"
"aqua:SurgeDM/Surge" = "latest"
bun = "latest"
cloudflared = "latest"
codex = "latest"
gh = "latest"
"github:alltuner/mise-completions-sync" = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
node = [ "lts", "latest" ]
opencode = "latest"
pnpm = "latest"
vercel = { version = "latest", allow_builds = [
  "esbuild",
], trust_policy_excludes = [
  "undici",
] }

[hooks]
postinstall = "misecompsync --shell zsh"
